// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Blog Post → tags*
 */
export interface BlogPostDocumentDataTagsItem {
	/**
	 * tag field in *Blog Post → tags*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	tag: prismic.ContentRelationshipField<'tags'>;
}

type BlogPostDocumentDataSlicesSlice =
	| TableBlockSlice
	| InfoBlockSlice
	| CodeBlockSlice
	| TextBlockSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * date field in *Blog Post*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Header image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.header_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	header_image: prismic.ImageField<never>;

	/**
	 * tags field in *Blog Post*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	tags: prismic.GroupField<Simplify<BlogPostDocumentDataTagsItem>>;

	/**
	 * Slice Zone field in *Blog Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
	 * Meta Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blog_post.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blog_post.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostDocumentData>,
	'blog_post',
	Lang
>;

type HomepageDocumentDataSlicesSlice =
	| BuyMeACoffeeSlice
	| RoadmapSlice
	| SeparatorSlice
	| HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

/**
 * Item in *Navigation → Navigation*
 */
export interface NavigationDocumentDataMainNavItem {
	/**
	 * Navigation item label field in *Navigation → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: home
	 * - **API ID Path**: navigation.main_nav[].nav_item_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nav_item_label: prismic.KeyTextField;

	/**
	 * Navigation item link field in *Navigation → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: /home
	 * - **API ID Path**: navigation.main_nav[].nav_item_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nav_item_link: prismic.LinkField;
}

/**
 * Item in *Navigation → Social Media Items*
 */
export interface NavigationDocumentDataSmItemsItem {
	/**
	 * Social Media Icon field in *Navigation → Social Media Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.sm_items[].sm_icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	sm_icon: prismic.ImageField<never>;

	/**
	 * Social Media Link field in *Navigation → Social Media Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: https://x.com
	 * - **API ID Path**: navigation.sm_items[].sm_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	sm_link: prismic.LinkField;
}

/**
 * Item in *Navigation → Policies*
 */
export interface NavigationDocumentDataPoliciesItem {
	/**
	 * policy label field in *Navigation → Policies*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Terms and conditions
	 * - **API ID Path**: navigation.policies[].policy_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	policy_label: prismic.KeyTextField;

	/**
	 * Policy link field in *Navigation → Policies*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.policies[].policy_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	policy_link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Navigation field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.main_nav[]
	 * - **Tab**: Main Navigation
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	main_nav: prismic.GroupField<Simplify<NavigationDocumentDataMainNavItem>> /**
	 * Social Media Items field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.sm_items[]
	 * - **Tab**: Social Media
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */;
	sm_items: prismic.GroupField<Simplify<NavigationDocumentDataSmItemsItem>> /**
	 * Copyright field in *Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Copyright © 2024 Codeperium by Rafal. All Rights Reserved.
	 * - **API ID Path**: navigation.copyright
	 * - **Tab**: Policy
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	copyright: prismic.KeyTextField;

	/**
	 * Policies field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.policies[]
	 * - **Tab**: Policy
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	policies: prismic.GroupField<Simplify<NavigationDocumentDataPoliciesItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationDocumentData>,
	'navigation',
	Lang
>;

type SubpageDocumentDataSlicesSlice = ContactFormSlice | HeroSlice;

/**
 * Content for Subpage documents
 */
interface SubpageDocumentData {
	/**
	 * Slice Zone field in *Subpage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: subpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SubpageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: subpage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: subpage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Subpage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: subpage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Subpage document from Prismic
 *
 * - **API ID**: `subpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SubpageDocumentData>,
	'subpage',
	Lang
>;

/**
 * Content for tags documents
 */
interface TagsDocumentData {
	/**
	 * tag field in *tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tags.tag
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tag: prismic.KeyTextField;
}

/**
 * tags document from Prismic
 *
 * - **API ID**: `tags`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<TagsDocumentData>,
	'tags',
	Lang
>;

export type AllDocumentTypes =
	| BlogPostDocument
	| HomepageDocument
	| NavigationDocument
	| SubpageDocument
	| TagsDocument;

/**
 * Default variation for BuyMeACoffee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BuyMeACoffeeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *BuyMeACoffee*
 */
type BuyMeACoffeeSliceVariation = BuyMeACoffeeSliceDefault;

/**
 * BuyMeACoffee Shared Slice
 *
 * - **API ID**: `buy_me_a_coffee`
 * - **Description**: BuyMeACoffee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BuyMeACoffeeSlice = prismic.SharedSlice<'buy_me_a_coffee', BuyMeACoffeeSliceVariation>;

/**
 * Primary content in *CodeBlock → Default → Primary*
 */
export interface CodeBlockSliceDefaultPrimary {
	/**
	 * language field in *CodeBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: code_block.default.primary.language
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	language: prismic.KeyTextField;

	/**
	 * filename field in *CodeBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: code_block.default.primary.filename
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	filename: prismic.KeyTextField;

	/**
	 * body field in *CodeBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: code_block.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for CodeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CodeBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CodeBlock*
 */
type CodeBlockSliceVariation = CodeBlockSliceDefault;

/**
 * CodeBlock Shared Slice
 *
 * - **API ID**: `code_block`
 * - **Description**: CodeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSlice = prismic.SharedSlice<'code_block', CodeBlockSliceVariation>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<'contact_form', ContactFormSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Codeperium
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Empire of coders
	 * - **API ID Path**: hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *InfoBlock → Default → Primary*
 */
export interface InfoBlockSliceDefaultPrimary {
	/**
	 * Severity field in *InfoBlock → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_block.default.primary.severity
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	severity: prismic.SelectField<'Success' | 'Warning' | 'Error'>;

	/**
	 * Heading field in *InfoBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_block.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Body field in *InfoBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_block.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for InfoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<InfoBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *InfoBlock*
 */
type InfoBlockSliceVariation = InfoBlockSliceDefault;

/**
 * InfoBlock Shared Slice
 *
 * - **API ID**: `info_block`
 * - **Description**: InfoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoBlockSlice = prismic.SharedSlice<'info_block', InfoBlockSliceVariation>;

/**
 * Item in *Roadmap → Default → Primary → Phase items*
 */
export interface RoadmapSliceDefaultPrimaryPhaseItemsItem {
	/**
	 * Label field in *Roadmap → Default → Primary → Phase items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.phase_items[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Status field in *Roadmap → Default → Primary → Phase items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.phase_items[].status
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	status: prismic.SelectField<'Not Started' | 'Work in Progress' | 'Finished'>;
}

/**
 * Primary content in *Roadmap → Default → Primary*
 */
export interface RoadmapSliceDefaultPrimary {
	/**
	 * Label field in *Roadmap → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Start Date field in *Roadmap → Default → Primary*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.start_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	start_date: prismic.DateField;

	/**
	 * Status field in *Roadmap → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Not Started
	 * - **API ID Path**: roadmap.default.primary.status
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	status: prismic.SelectField<'Not Started' | 'Work in Progress' | 'Finished', 'filled'>;

	/**
	 * Phase Name field in *Roadmap → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.phase_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	phase_name: prismic.KeyTextField;

	/**
	 * Phase items field in *Roadmap → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: roadmap.default.primary.phase_items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	phase_items: prismic.GroupField<Simplify<RoadmapSliceDefaultPrimaryPhaseItemsItem>>;
}

/**
 * Default variation for Roadmap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoadmapSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RoadmapSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Roadmap*
 */
type RoadmapSliceVariation = RoadmapSliceDefault;

/**
 * Roadmap Shared Slice
 *
 * - **API ID**: `roadmap`
 * - **Description**: Roadmap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoadmapSlice = prismic.SharedSlice<'roadmap', RoadmapSliceVariation>;

/**
 * Primary content in *Separator → Default → Primary*
 */
export interface SeparatorSliceDefaultPrimary {
	/**
	 * Icon field in *Separator → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: separator.default.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Label field in *Separator → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Roadmap
	 * - **API ID Path**: separator.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for Separator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeparatorSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SeparatorSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Separator*
 */
type SeparatorSliceVariation = SeparatorSliceDefault;

/**
 * Separator Shared Slice
 *
 * - **API ID**: `separator`
 * - **Description**: Separator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeparatorSlice = prismic.SharedSlice<'separator', SeparatorSliceVariation>;

/**
 * Primary content in *TableBlock → Default → Primary*
 */
export interface TableBlockSliceDefaultPrimary {
	/**
	 * table field in *TableBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: table_block.default.primary.table
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	table: prismic.RichTextField;
}

/**
 * Default variation for TableBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TableBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TableBlock*
 */
type TableBlockSliceVariation = TableBlockSliceDefault;

/**
 * TableBlock Shared Slice
 *
 * - **API ID**: `table_block`
 * - **Description**: TableBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableBlockSlice = prismic.SharedSlice<'table_block', TableBlockSliceVariation>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
	/**
	 * Subheading field in *TextBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_block.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * body field in *TextBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_block.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogPostDocument,
			BlogPostDocumentData,
			BlogPostDocumentDataTagsItem,
			BlogPostDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataMainNavItem,
			NavigationDocumentDataSmItemsItem,
			NavigationDocumentDataPoliciesItem,
			SubpageDocument,
			SubpageDocumentData,
			SubpageDocumentDataSlicesSlice,
			TagsDocument,
			TagsDocumentData,
			AllDocumentTypes,
			BuyMeACoffeeSlice,
			BuyMeACoffeeSliceVariation,
			BuyMeACoffeeSliceDefault,
			CodeBlockSlice,
			CodeBlockSliceDefaultPrimary,
			CodeBlockSliceVariation,
			CodeBlockSliceDefault,
			ContactFormSlice,
			ContactFormSliceVariation,
			ContactFormSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			InfoBlockSlice,
			InfoBlockSliceDefaultPrimary,
			InfoBlockSliceVariation,
			InfoBlockSliceDefault,
			RoadmapSlice,
			RoadmapSliceDefaultPrimaryPhaseItemsItem,
			RoadmapSliceDefaultPrimary,
			RoadmapSliceVariation,
			RoadmapSliceDefault,
			SeparatorSlice,
			SeparatorSliceDefaultPrimary,
			SeparatorSliceVariation,
			SeparatorSliceDefault,
			TableBlockSlice,
			TableBlockSliceDefaultPrimary,
			TableBlockSliceVariation,
			TableBlockSliceDefault,
			TextBlockSlice,
			TextBlockSliceDefaultPrimary,
			TextBlockSliceVariation,
			TextBlockSliceDefault
		};
	}
}
