// Code generated by Slice Machine. DO NOT EDIT.

import BlogPosts from './BlogPosts/index.svelte';
import BuyMeACoffee from './BuyMeACoffee/index.svelte';
import CodeBlock from './CodeBlock/index.svelte';
import ContactForm from './ContactForm/todo.svelte';
import Hero from './Hero/index.svelte';
import InfoBlock from './InfoBlock/index.svelte';
import Roadmap from './Roadmap/index.svelte';
import Separator from './Separator/index.svelte';
import TableBlock from './TableBlock/index.svelte';
import TextBlock from './TextBlock/index.svelte';

export const components = {
	blog_posts: BlogPosts,
	buy_me_a_coffee: BuyMeACoffee,
	code_block: CodeBlock,
	contact_form: ContactForm,
	hero: Hero,
	info_block: InfoBlock,
	roadmap: Roadmap,
	separator: Separator,
	table_block: TableBlock,
	text_block: TextBlock
};
