// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero/index.svelte';
import Roadmap from './Roadmap/index.svelte';
import Separator from './Separator/index.svelte';

export const components = {
	hero: Hero,
	roadmap: Roadmap,
	separator: Separator
};
